Domain\Entities\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: company_id
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 8
            scale: 2
        image:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        ncm:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        sku:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        upc:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        model:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        weight:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        length:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        height:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        width:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    oneToMany:
        categories:
            targetEntity: Domain\Entities\ProductCategory
            mappedBy: product
            cascade: [persist, remove]

    lifecycleCallbacks: {  }
